### ISSUE TITLE
Unfortunate error appears to have occured

### ISSUE THREAD

**Issue by meza** [renderbot/renderbot#2]
I'm trying to process a queue with the newest AMI, but whenever I request an instance to be created, I get an unfortunate error.

Where can I see the logs? They might contain something useful.
I've tried different instance types, but nothing works. Everything else seems to work, but the instance creation :(

**Comment by amalganimation** [comment]
One can redirect errors  into a file, to do this:
- press `5 - Exit` to get to the shell.
- type `renderbot 2>out.err` and press Enter. 
- Try to start an instance and let it fail
- press `5 - Exit` to get to the shell.
- type `less out.err` to see any AWS error messages
